config/routes.rb
Lctv::Application.routes.draw do

  # home
  root :controller => 'home' , :action => 'home'

  # auth
  get  '/signin'                  , :to => 'sessions#new'     , :as => :signin
  get  '/signout'                 , :to => 'sessions#destroy' , :as => :signout
  post '/auth/:provider/callback' , :to => 'sessions#create'
  get  '/auth/failure'            , :to => 'sessions#fail'

  # users
  get    'users'            => 'users#index'   , :as => 'users'
  get    'users/:nick'      => 'users#show'    , :as => 'user'
  get    'users/:nick/edit' => 'users#edit'    , :as => 'edit_user'
  patch  'users/:nick'      => 'users#update'
  put    'users/:nick'      => 'users#update'
  delete 'users/:nick'      => 'users#destroy'

  # projects
  resources :projects

  # polls
  resources :polls
  post '/polls/votes' , :to => 'votes#create' , :as => :vote

  # misc
  get 'forum'     => 'home#forum'
  get 'badges'    => 'home#badges'
  get 'emoticons' => 'home#emoticons'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :polls
  has_many :votes        , :dependent => :destroy
  has_many :poll_options , :through   => :votes

  validates :nick , :uniqueness => { case_sensitive: false } , :presence => true
  validates :uid  , :uniqueness => { case_sensitive: false } , :presence => true


  def self.find_or_create_with_omniauth auth_hash
    # FIXME: we may want not at all to handle developer strategy
    auth_hash[:uid] = "developer-#{Time.now.to_i}" if auth_hash[:provider] == 'developer'

    # sanitize auth hash
    auth_hash                 = {}        unless auth_hash                .is_a? Hash
    auth_hash[:info]          = {}        unless auth_hash[:info]         .is_a? Hash
    auth_hash[:uid ]          = ''        unless auth_hash[:uid ]         .is_a? String
    auth_hash[:info][:name  ] = ''        unless auth_hash[:info][:name  ].is_a? String
    auth_hash[:info][:avatar] = MM_AVATAR unless auth_hash[:info][:avatar].is_a? String

    # normalize params
    uid    =   auth_hash[:uid ]
    nick   = ((auth_hash[:info][:name].match NICK_REGEX) || [])[0]
    avatar =   auth_hash[:info][:avatar]

    self.find_or_create_by! :nick => nick do | a_user |
      a_user.uid    = uid
      a_user.nick   = nick
      a_user.avatar = avatar
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user           , only: [ :show , :edit , :update , :destroy ]
  before_action :authorize_for_user , only: [         :edit , :update , :destroy ]


  def index ; @users = User.all ; end ;

  def show ; end ;

  def edit ; end ;

  def update
    is_valid_update = params[:user][:nick] == @user.nick &&
                      params[:user][:uid ] == @user.uid

    if is_valid_update && (@user.update user_params)
      redirect_to @user , :notice => [ "Status" , "User was successfully updated" ]
    else
      render action: 'edit' , :alert => "Uknown error - Try again"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end


private

  def set_user
    is_friendly_url = params[:nick].to_i == 0
    @user           = is_friendly_url ? (User.find_by_nick params[:nick]) :
                                        (User.find         params[:nick])
    params[:nick]   = @user.nick if @user.present?

    redirect_to users_path unless @user.present?
  end

  def authorize_for_user
    redirect_to @user , :alert => "Access denied" unless authorized_for_user? @user
  end

  def user_params
    required_params  = params.require :user
    permitted_params = required_params.permit :nick , :uid , :bio , :avatar , :is_admin
    permitted_params.require :nick
    permitted_params.require :uid
    permitted_params
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render :partial => 'shared/edit_nav' , :locals => { :object     => @user      ,
                                                        :index_path => users_path } %>


<h1>Editing <%= @user.nick %>'s Profile</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if admin? %>
    <div class="field">
      <%= f.label      :nick %><br>
      <%= f.text_field :nick %>
    </div>
    <div class="field">
      <%= f.label      :uid %><br>
      <%= f.text_field :uid %>
    </div>
    <div class="field">
      <%= f.label     :is_admin %><br>
      <%= f.check_box :is_admin %>
    </div>
  <% else %>
      <%= f.hidden_field :nick     %>
      <%= f.hidden_field :uid      %>
      <%= f.hidden_field :is_admin %>
  <% end %>

  <div class="field">
    <%= f.label      :bio %><br>
    <%= f.text_field :bio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Nick</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nick %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% edit_path = (authorized_for_user? @user) ? (edit_user_path @user) : '' %>
<%= render :partial => 'shared/show_nav' , :locals => { :object     => @user      ,
                                                        :index_path => users_path ,
                                                        :edit_path  => edit_path  } %>

<h1><%= @user.nick %>'s Profile</h1>

<p><strong>Bio:</strong></p><p><%= @user.bio %></p>