config/routes.rb
Lctv::Application.routes.draw do

  # home
  root :controller => 'home' , :action => 'home'

  # auth
  get  '/signin'                  , :to => 'sessions#new'     , :as => :signin
  get  '/signout'                 , :to => 'sessions#destroy' , :as => :signout
  post '/auth/:provider/callback' , :to => 'sessions#create'
  get  '/auth/failure'            , :to => 'sessions#fail'

  # users
  get    'users'            => 'users#index'   , :as => 'users'
  get    'users/:nick'      => 'users#show'    , :as => 'user'
  get    'users/:nick/edit' => 'users#edit'    , :as => 'edit_user'
  patch  'users/:nick'      => 'users#update'
  put    'users/:nick'      => 'users#update'
  delete 'users/:nick'      => 'users#destroy'

  # projects
  resources :projects

  # polls
  resources :polls
  post '/polls/votes' , :to => 'votes#create' , :as => :vote

  # misc
  get 'forum'     => 'home#forum'
  get 'badges'    => 'home#badges'
  get 'emoticons' => 'home#emoticons'

end

app/views/shared/_edit_nav.html.erb
<%= link_to '<-- Back' , index_path %> <%= link_to 'Cancel' , object %>

app/views/shared/_flash.html.erb
<% flash.each do | title , message | %>
  <div class="flash-div flash-<%= title %>">
    <% title , message = message if message.is_a? Array %>
    <h3 class="flash-header-h3"><%= title %>:</h3>
    <span class="flash-message-span"><%= message %></span>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<span id="top-nav-l-span" class="top-nav-cell">
  <a href="<%= LCTV_URL %>" id="top-nav-logo-a">
    <%= image_tag 'lctv-users-logo.png' , :alt => 'livecoding.tv logo' %>
  </a>
</span>

<span id="top-nav-c-span" class="top-nav-cell">
  <a href="/">Home</a>
  <a href="<%= LCTV_PROJECTS_URL  %>">Projects</a>
  <a href="<%= LCTV_USERS_URL     %>">Users</a>
  <a href="<%= LCTV_FORUM_URL     %>">Forum</a>
  <a href="<%= LCTV_POLLS_URL     %>">Polls</a>
  <a href="<%= LCTV_BADGES_URL    %>">Badges</a>
  <a href="<%= LCTV_EMOTICONS_URL %>">Emoticons</a>
</span>

<span id="top-nav-r-span" class="top-nav-cell">
  <% if not signed_in? %>
    <a href="<%= signin_path %>"   ><span id="signin-span">LOGIN</span></a>
    <a href="<%= LCTV_URL %>signup"><span id="signup-span">SIGN UP</span></a>
  <% else %>
    <% mail_url   = LCTV_URL + current_user.nick   + '/settings/messages/'      %>
    <% alerts_url = LCTV_URL + current_user.nick   + '/settings/notifications/' %>
    <% fans_url   = LCTV_URL + current_user.nick   + '/settings/followers/'     %>
    <% user_url   = LCTV_URL + current_user.nick   + '/'                        %>
    <% avatar_url =            current_user.avatar                              %>

    <a href="<%= mail_url     %>" id="top-nav-mail-a"  >
      <%= image_tag 'mail.png'    , :id  => 'top-nav-mail-img'   , :alt => "messages"      %>
    </a>
    <a href="<%= alerts_url   %>" id="top-nav-alerts-a">
      <%= image_tag 'bell.png'    , :id  => 'top-nav-alerts-img' , :alt => "notifications" %>
    </a>
    <a href="<%= fans_url     %>" id="top-nav-fans-a"  >
      <%= image_tag 'follows.png' , :id  => 'top-nav-fans-img'   , :alt => "follows"       %>
    </a>
    <a href="<%= signout_path %>" id="top-nav-user-a"  >
      <%= image_tag avatar_url    , :id  => 'top-nav-user-img'   , :alt => "avatar"        %>
    </a>
  <% end %>
</span>

app/views/shared/_new_nav.html.erb
<%= link_to '<-- Back' , index_path %>

app/views/shared/_show_nav.html.erb
<%= link_to '<-- Back' , index_path %>
<% if edit_path.present? %>&nbsp;|&nbsp;
<%= link_to 'Edit'     , edit_path  %>&nbsp;|&nbsp;
<%= link_to 'Destroy'  , object , :method => :delete , :data => { confirm: 'Are you sure?' } %>
<% end %>