config/routes.rb
Lctv::Application.routes.draw do

  # home
  root :controller => 'home' , :action => 'home'

  # auth
  get  '/signin'                  , :to => 'sessions#new'     , :as => :signin
  get  '/signout'                 , :to => 'sessions#destroy' , :as => :signout
  post '/auth/:provider/callback' , :to => 'sessions#create'
  get  '/auth/failure'            , :to => 'sessions#fail'

  # users
  get    'users'            => 'users#index'   , :as => 'users'
  get    'users/:nick'      => 'users#show'    , :as => 'user'
  get    'users/:nick/edit' => 'users#edit'    , :as => 'edit_user'
  patch  'users/:nick'      => 'users#update'
  put    'users/:nick'      => 'users#update'
  delete 'users/:nick'      => 'users#destroy'

  # projects
  resources :projects

  # polls
  resources :polls
  post '/polls/votes' , :to => 'votes#create' , :as => :vote

  # misc
  get 'forum'     => 'home#forum'
  get 'badges'    => 'home#badges'
  get 'emoticons' => 'home#emoticons'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many   :poll_options
  has_many   :votes , :dependent => :destroy
  belongs_to :user
  belongs_to :project

  validates_associated :user
  validates :topic   , :presence => true
  validates :user_id , :presence => true
  validates :user    , :presence => true

  accepts_nested_attributes_for :poll_options , :reject_if => :all_blank , :allow_destroy => true
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll           , :only => [ :show , :edit , :update , :destroy ]
  before_action :authenticate_user  , :only => [ :new  , :create ]
  before_action :set_option         , :only => [ :show ]
  before_action :set_projects       , :only => [ :new  , :edit , :create , :update ]
  before_action :authorize_for_poll , :only => [ :edit , :update , :destroy ]


  def index ; @polls = Poll.all ; end ;

  def show ; end ;

  def new ; @poll = Poll.new ; end ;

  def edit ; end ;

  def create
    @poll = current_user.polls.create poll_params

    if @poll.save
      redirect_to edit_poll_path @poll , :notice => [ "Status" , "Poll was successfully created" ]
    else
      render action: 'new' , :alert => "Unknown error - Try again"
    end
  end

  def update
    if @poll.update poll_params
      redirect_to @poll , notice: 'Poll was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @poll.destroy
    redirect_to polls_url , notice: 'Poll was successfully destroyed.'
  end


private

  def set_poll
    @poll = Poll.includes(:poll_options).find_by_id params[:id]
  end

  def set_option
    @selected_option = current_user.poll_options.find_by_poll_id @poll.id if signed_in?
  end

  def set_projects
    @projects = current_user.projects.all.order :name
  end

  def authorize_for_poll
    redirect_to @poll , :alert => "Access denied" unless authorized_for_poll? @poll
  end

  def poll_params
    params.require(:poll).permit :topic , :is_open , :project_id ,
                                 :poll_options_attributes => [ :id , :option , :is_other , :poll_id , :_destroy ]
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :topic %>:<br>
    <%= f.text_area :topic , :size => "25x1" , :required => true %>
  </div>
  <% unless @poll.new_record? %><br>
    <div class="field">
      <%= f.label :is_open %>?:<br>
      <%= f.check_box :is_open %>
    </div>
  <% end %>

  <!-- belongs_to Project association -->
  <% if @projects.count > 0 %>
    <div>Project: </div>
    <%= f.collection_select :project_id , @projects , :id , :name , :include_blank => POLL_PROJECT_PROMPT %>
  <% end %>

  <!-- has_many PollOption nested association -->
  <% unless @poll.new_record? %><!-- FIXME: -->
    <div>Poll Options: </div>
      <div>
        <%= f.fields_for :poll_options do | options_form | %>
          <%= render 'poll_option_fields' , :f => options_form %>
        <% end %>

        <div class="links">
          <%= link_to_add_association 'Add Option' , f , :poll_options %>
        </div>
        <div class="links">
     <!-- <%= link_to_add_association 'Add "Other" Option' , f , :poll_options %> --><!-- TODO: -->
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/polls/_poll_option.html.erb
<li>
  <%= content_tag :label do %>
    <% is_selected = poll_option.id == selected_option_id %>

    <%= radio_button_tag 'poll_option[id]' , poll_option.id , is_selected , :onclick => "document.getElementById('vote_form').querySelector('input[type=submit]').style.display = '#{is_selected ? 'none' : 'inline'}' ;" %>
    <%= poll_option.option %>
  <% end %>
</li>

app/views/polls/_poll_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.text_field :option , :required => true %>
    <%= link_to_remove_association "Remove Option" , f %>
  </div>
</div>

app/views/polls/_vote_form.html.erb
<%= form_tag vote_path , :method => :post , :remote => true , :id => 'vote_form' do %>
  <%= hidden_field_tag 'poll[id]' , @poll.id %>

  <% if @poll.poll_options.size > 0 %>
    <strong>Poll Options: </strong>
    <ul>
      <% selected_option_id = @selected_option.id if @selected_option.present? %>
      <%= render :partial    => 'polls/poll_option'                           ,
                 :collection => @poll.poll_options                            ,
                 :as         => :poll_option                                  ,
                 :locals     => { :selected_option_id => selected_option_id } %>
    </ul>

    <%= submit_tag 'Vote' , :style => "display: none ;" %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<%= render :partial => 'shared/edit_nav' , :locals => { :object     => @poll      ,
                                                        :index_path => polls_path } %>

<h1>Editing poll</h1>

<%= render 'form' %>

app/views/polls/index.html.erb
<p><%= link_to 'New Poll' , new_poll_path %></p>

<h1>Listing polls</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <% if admin? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <% next unless poll.is_open %>

      <tr>
        <td><%= link_to poll.topic , poll %></td>
        <% if admin? %>
          <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
          <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/polls/new.html.erb
<%= render :partial => 'shared/new_nav' , :locals => { :index_path => polls_path } %>

<h1>New poll</h1>

<%= render 'form' %>

app/views/polls/show.html.erb
<% edit_path = (authorized_for_poll? @poll) ? (edit_poll_path @poll) : '' %>
<%= render :partial => 'shared/show_nav' , :locals => { :object     => @poll      ,
                                                        :index_path => polls_path ,
                                                        :edit_path  => edit_path  } %>

<p>
  <strong>Topic: </strong>
  <%= @poll.topic %>
</p>

<p>
  <strong>Maintainer: </strong>
  <%= @poll.user.nick %>
</p>

<% if @poll.project.present? %>
  <p>
    <strong>Project: </strong>
    <%= @poll.project.name %>
  </p>
<% end %>

<% if authorized_for_poll? @poll %>
<p>
  <strong>Is open?: </strong>
  <%= @poll.is_open %>
</p>
<% end %>

<%= render 'vote_form' %>