config/routes.rb
Lctv::Application.routes.draw do

  # home
  root :controller => 'home' , :action => 'home'

  # auth
  get  '/signin'                  , :to => 'sessions#new'     , :as => :signin
  get  '/signout'                 , :to => 'sessions#destroy' , :as => :signout
  post '/auth/:provider/callback' , :to => 'sessions#create'
  get  '/auth/failure'            , :to => 'sessions#fail'

  # users
  get    'users'            => 'users#index'   , :as => 'users'
  get    'users/:nick'      => 'users#show'    , :as => 'user'
  get    'users/:nick/edit' => 'users#edit'    , :as => 'edit_user'
  patch  'users/:nick'      => 'users#update'
  put    'users/:nick'      => 'users#update'
  delete 'users/:nick'      => 'users#destroy'

  # projects
  resources :projects

  # polls
  resources :polls
  post '/polls/votes' , :to => 'votes#create' , :as => :vote

  # misc
  get 'forum'     => 'home#forum'
  get 'badges'    => 'home#badges'
  get 'emoticons' => 'home#emoticons'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates_associated :user

  validates :name    , uniqueness: { case_sensitive: false } , :presence    => true
  validates :repo    , uniqueness: { case_sensitive: false } , :allow_blank => true
  validates :user_id ,                                         :presence => true
  validates :user    ,                                         :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project           , :only => [ :edit , :update , :destroy , :show ]
  before_action :authorize_for_project , :only => [ :edit , :update , :destroy ]
  before_action :authenticate_user     , :only => [ :new , :create ]


  def index ; @projects = Project.all ; end ;

  def show ; end ;

  def new ; @project = Project.new ; end ;

  def edit ; end ;

  def create
    @project = current_user.projects.create project_params

    if @project.save
      redirect_to @project , :notice => [ "Status" , "Project was successfully created" ]
    else
      render action: 'new' , :alert => "Unknown error - Try again"
    end
  end

  def update
    if @project.update project_params
      redirect_to @project , notice: [ "Status" , "Project was successfully updated" ]
    else
      render action: 'edit' , :alert => "Unknown error - Try again"
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end


private

  def set_project
    @project = Project.find(params[:id])
  end

  def authorize_for_project
    redirect_to @project , :alert => "Access denied" unless authorized_for_project? @project
  end

  def project_params
    ((params[:params] || params).require :project).permit :name , :repo , :desc , :user_id
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label      :name %><br>
    <%= f.text_field :name %>
  </div>
  <% unless @project.new_record? %>
    <div class="field">
      <%= "Maintainer"       %><br>
      <%= @project.user.nick %>
    </div>
  <% end %>
  <div class="field">
    <%= "Repo URL"         %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :desc     %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render :partial => 'shared/edit_nav' , :locals => { :object     => @project      ,
                                                        :index_path => projects_path } %>

<h1>Editting <%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects created by LiveCoding.TV streamers</h1>

<%= link_to 'Add Project' , new_project_path %>

<table id="projects-table">
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class="projects-name-td"><%= link_to project.name , project %></td>
        <td class="projects-desc-td"><%= project.desc %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<%= render :partial => 'shared/new_nav' , :locals => { :index_path => projects_path } %>

<h1>Add Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<% edit_path = (authorized_for_project? @project) ? (edit_project_path @project) : '' %>
<%= render :partial => 'shared/show_nav' , :locals => { :object     => @project      ,
                                                        :index_path => projects_path ,
                                                        :edit_path  => edit_path     } %>

<h1><%= @project.name %></h1>

<p><strong>Maintainer:</strong></p>
<%= @project.user.nick %>

<% if @project.repo.present? %>
  <div>
    <p><strong>Repo URL:</strong></p>
    <%= link_to @project.repo , @project.repo %>
  </div>
<% end %>

<p>&nbsp;</p>

<div>
  <p><strong>Description:</strong></p>
  <%= @project.desc %>
</div>